#!/bin/zsh
# . Récupérez la liste des interfaces réseau de la machine sans afficher aucun détail
# pour ces interfaces. Vraiment juste la liste des noms.

ifconfig -l

# Interfaces reseaux actives
# ifconfig | grep "UP" | cut -d ":" -f1

# ifconfig | grep ": flags=" | cut -d ":" -f1
