#!/bin/zsh
#	Identifier l'adresse MAC de la carte Wifi

ifconfig en1 | grep ether | cut -d " " -f2 

# voir dans le fichier pour connaitre les noms des interfaces 
#  NetworkInterfaces.plist
#  networksetup -listallhardwareports
