#!/bin/zsh

#Identifiez la gateway par défaut dans la table de routage

netstat -rn | grep default | grep en0

# nestat -nr | head -n 5 | tail -2
# netstat -nr | grep -Ei "defaul.*en0"


### COLOR: 04 BLUE