#!/bin/zsh
# Trouvez une commande qui, en parallèle de la session graphique, permet de se
#	connecter en ssh sur la machine


# ssh user@IP -p x (x = {1024, 65535}, par default x = 22)
#	avec la configuration de la NAT pour la VM, x = 2223

ssh lena@127.0.0.1 -p 2223



### COLOR: 17 BLUE
